apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: health-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 756033365011.dkr.ecr.ap-south-1.amazonaws.com/myrepo:v1
        ports: 
        - containerPort: 80 
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "521Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
          initialDelaySeconds: 3
          periodSeconds: 3
      imagePullSecrets:
      - name: regcred
